<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document [

<!ELEMENT document (line+)>
<!ATTLIST document description CDATA #IMPLIED>

<!ELEMENT line (key*, field+)>
<!ATTLIST line
  name ID #REQUIRED
  tablename CDATA #REQUIRED
  action (INSERT|UPDATE|INSERT_UPDATE|DELETE|SHOW) 'INSERT_UPDATE'
  trigger_class_name CDATA #IMPLIED
>

<!ELEMENT key (#PCDATA)>
<!ATTLIST key
  value CDATA #REQUIRED
  startposition CDATA #REQUIRED
  size CDATA #REQUIRED
>

<!ELEMENT field ((string|integer|long|float|double|datetime), (position|constante|query) , check_in?)>
<!ATTLIST field
  fieldname CDATA #REQUIRED
  nullable (true|false) 'true'
  nullable_error (true|false) 'true'
  isuse (true|false) 'true'
>

<!ELEMENT position (#PCDATA)>
<!ATTLIST position
  startposition CDATA #REQUIRED
  size CDATA #REQUIRED
>

<!ELEMENT constante (#PCDATA)>
<!ATTLIST constante
  value CDATA #REQUIRED
>

<!-- requête -->
<!ELEMENT query (query-param*)>
<!ATTLIST query
  sql CDATA #REQUIRED
>

<!ELEMENT query-param ((string|integer|long|float|double|datetime), (position|constante))>

<!ELEMENT string EMPTY>

<!ELEMENT integer EMPTY>
<!ATTLIST integer coefficient CDATA #IMPLIED>

<!ELEMENT long EMPTY>
<!ATTLIST long coefficient CDATA #IMPLIED>

<!ELEMENT float EMPTY>
<!ATTLIST float coefficient CDATA #IMPLIED>

<!ELEMENT double EMPTY>
<!ATTLIST double coefficient CDATA #IMPLIED>

<!ELEMENT datetime EMPTY>
<!ATTLIST datetime dateformat CDATA #REQUIRED>

<!-- requête -->

<!ELEMENT check_in EMPTY>
<!ATTLIST check_in
  sql CDATA #REQUIRED
>
]>
<document description="File de test !">
<!-- trigger_class_name="org.jobjects.dbimp.trigger.MyTrigger" -->
<line name="MYTABLE" tablename="MYTABLE">
  <key value="MYTABLE" startposition="0" size="7"/>
  <field fieldname="MONCHAMPSTEXTE"><string/><position startposition="7" size="6"/></field>
  <field fieldname="MONCHAMPSCHAR"><string/><position startposition="13" size="2"/></field>
  <field fieldname="MONCHAMPSDATE"><datetime dateformat="MM/dd/yyyy"/><position startposition="15" size="10"/></field>
  <field fieldname="MONCHAMPSDATETIME"><datetime dateformat="MM/dd/yyyy HH:mm:ss"/><position startposition="25" size="19"/></field>
  <field fieldname="MONCHAMPSDECIMAL"><double/><position startposition="44" size="3"/></field>
</line>
<line name="SECU_USER" tablename="SECU_USER">
  <key value="SECU_USER" startposition="0" size="9"/>
  <field fieldname="USERNAME"><string/><position startposition="9" size="10"/></field>
  <field fieldname="PASSWORD"><string/><position startposition="19" size="10"/></field>
  <field fieldname="MONCHAMPSDATETIME"><datetime dateformat="MM/dd/yyyy HH:mm:ss"/><position startposition="29" size="19"/></field>
</line>
<line name="SECU_USER_ROLE" tablename="SECU_USER_ROLE">
  <key value="SECU_USER_ROLE" startposition="0" size="19"/>
  <field fieldname="USERNAME"><string/><position startposition="19" size="35"/></field>
  <field fieldname="ROLENAME"><string/><position startposition="54" size="20"/></field>
  <field fieldname="MONCHAMPSDATETIME"><datetime dateformat="MM/dd/yyyy HH:mm:ss"/><position startposition="25" size="19"/></field>
</line>
</document>
